### ISSUE TITLE
cant download test fastq from ftp

### ISSUE THREAD

**Issue by glichtenstein** [warrenlr/TASR#2]
wget ftp://ftp.bcgsc.ca/supplementary/SSAKE/SRR066437.fastq.bz2
2019-03-11 14:27:20 ERROR 404: Not Found.

**Comment by warrenlr** [comment]
Our FTP was retired a few months back and the URLs have not yet been re-routed.  

The path to the data you are looking for is:
http://www.bcgsc.ca/downloads/supplementary/SSAKE/SRR066437.fastq.bz2

I apologize for the inconvenience.
Rene
