### ISSUE TITLE
-t 0?

### ISSUE THREAD

**Issue by Sanrrone** [warrenlr/TASR#3]
Dears,
I was using TASR to improve a previous assembly and I have some questions.

1) after running [v1.6.2], appear a  **-t 0** , but there is no info about what is that flag. it is for threads?
2) My previous assembly have 2000 contigs. My idea is to use my new sequences to improve the assembly and have (if is possible), less than 2000 contigs. but, my reads are from a whole genome eukaryotic sequencing and my contigs are just one chromosome (yeah, 2000 contigs annotated as one chromosome). is this the correct software for my purpose? I mean, just want the assembly which my reads overlap/extend my contigs.
3) is there a way to increase the performance if -t is not for threads?

thanks in advance

**Comment by warrenlr** [comment]
hello and thank you for your interest in TASR.

Below some answers to your questions:
1.  TASR is written in PERL and is NOT multithreaded. It will run on a single CPU.  There is no -t options, as per the README

2. Have you considered scaffolding, then gap filling?  What sequencing data do you have (eg. short, linked, long reads?)
We offer solutions for scaffolding with these data types at https://github.com/bcgsc.  (eg. ARCS, LINKS, abyss-scaffold, sealer).  You can try to extend your contigs by running TASR with -i 0.  It is unknown whether you will be able to extend your contigs substantially, but no harm in trying.  But in the end, you will still be left with the same number of contigs, and will have to find a way to merge them, which is what a scaffolder does.  If you want to scaffold using a reference, please check out ntJoin.  The sequence will be preserved, but the structure will be borrowed from the reference sequence you use.

3. no, sorry

**Comment by Sanrrone** [comment]
I have my scaffolds from a Chromosome and I want to do the gap filling (or extend the contigs). I have the assembly and 300Millions of Illumina reads PE. I was using TASR but is slow in reading the candidates it's takes 1 hour per 10M reads. Do you know some software?

Thanks in advance

**Comment by warrenlr** [comment]
you may be able to run abyss-scaffold, then sealer. @lcoombe what do you think?

**Comment by lcoombe** [comment]
Hi @Sanrrone ,

Yes, you could run `abyss-scaffold` to contiguate your assembly further using the PE reads -- this would essentially involve running the `scaffold` stage of ABySS. Roughly, you'd align the PE reads to your existing assembly, then run `abyss-scaffold` to detect paths suggested by the PE evidence. You could take a look at the `abyss-pe` Makefile in ABySS, but if you are interested in this, I can help you out with the commands to run - it isn't super straightforward.

For gap-filling, yes definitely Sealer is a good choice.

Adding onto Rene's suggestion with ntJoin, another option with ntJoin could be to do a quick ABySS assembly of your new reads, and then use one of your assemblies to improve the other. (Essentially using the ABySS assembly as the 'reference' for ntJoin).

**Comment by Sanrrone** [comment]
Hi,
The ntJoin approach works perfect, I made a new assembly and then combine them for a better scaffolding step.
thanks!

**Comment by lcoombe** [comment]
Great! I'm glad that worked well for you :)
